# Generated by Django 3.2.6 on 2021-10-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_content', models.TextField(blank=True, null=True, verbose_name='Полное Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('img_name', models.CharField(max_length=100, verbose_name='Путь к изображению(src/photo.png)')),
                ('on_stock', models.BooleanField(default=False, verbose_name='Есть ли акция?')),
                ('stock_price', models.FloatField(blank=True, null=True, verbose_name='Цена по акции')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Обьявление',
                'verbose_name_plural': 'Обьявления',
                'ordering': ['-published'],
            },
        ),
    ]
